#!/bin/bash
BUILDDIR=linux32
if [ -z $BUILDDIR/stagehand ] 
then
  echo "Must build first before creating package" 
  exit 1
fi
PLATFORM=`uname`
ARCH=x86
ARCHNAME=i386

. ./createstagehandupdate_main.sh $BUILDDIR 
