#!/bin/bash
if [ -z "$STAGEHAND_BIN_COMPILE_LOCATION" ] 
then
  echo "Must set STAGEHAND_BIN_COMPILE_LOCATION"
  exit 1
fi
PLATFORM=`uname`
ARCH=`uname -m`
VERSION=`$STAGEHAND_BIN_COMPILE_LOCATION/stagehand --version`

if [ "$ARCH" == "x86_64" ]
then
   ARCH=amd64
else
   ARCH=i386
fi

BASEDIR=stagehand_${VERSION}_${ARCH}
mkdir -p $BASEDIR/DEBIAN
cp deb/control $BASEDIR/DEBIAN
cp deb/postrm $BASEDIR/DEBIAN
cp deb/postinst $BASEDIR/DEBIAN
echo "Architecture: "$ARCH >> $BASEDIR/DEBIAN/control
echo "Version: "$VERSION >> $BASEDIR/DEBIAN/control

mkdir -p $BASEDIR/usr/share/applications
mkdir -p $BASEDIR/usr/share/stagehand
mkdir -p $BASEDIR/usr/share/stagehand/bin
mkdir -p $BASEDIR/usr/share/stagehand/bin/android
mkdir -p $BASEDIR/usr/share/stagehand/bin/tizen
mkdir -p $BASEDIR/usr/share/stagehand/bin/ubuntu

cp deb/Stagehand.desktop $BASEDIR/usr/share/applications/
cp ../stagehand.png $BASEDIR/usr/share/stagehand/stagehand.png
cp stagehand $BASEDIR/usr/share/stagehand/stagehand
cp $STAGEHAND_BIN_COMPILE_LOCATION/stagehand $BASEDIR/usr/share/stagehand/bin/
cp -R android $BASEDIR/usr/share/stagehand/bin
cp -R tizen $BASEDIR/usr/share/stagehand/bin
cp -R ubuntu $BASEDIR/usr/share/stagehand/bin

chmod -R 755 $BASEDIR
chmod 644 $BASEDIR/usr/share/applications/Stagehand.desktop
chmod 644 $BASEDIR/usr/share/stagehand/stagehand.png

fakeroot dpkg-deb --build $BASEDIR

zip -r --symlinks $PLATFORM"_update"$VERSION.zip $BASEDIR.deb doUpdate
$STAGEHAND_BIN_COMPILE_LOCATION/stagehand --versioninfo > version_info_$PLATFORM.txt
