#!/bin/bash
if [ -z "$QT5_ROOT" ] 
then
  echo "Must set QT5_ROOT"
  exit 1
fi
PLATFORM=`uname`
ARCH=`uname -m`
VERSION=1.01

if [ "$ARCH" == "x86_64" ]
then
   ARCH=amd64
else
   ARCH=i386
fi

BASEDIR=stagehand-qtdeps_${VERSION}_${ARCH}
mkdir -p $BASEDIR/DEBIAN
cp deb/qtdeps_control $BASEDIR/DEBIAN/control
echo "Architecture: "$ARCH >> $BASEDIR/DEBIAN/control
echo "Version: "$VERSION >> $BASEDIR/DEBIAN/control

mkdir -p $BASEDIR/usr/share/stagehand/lib
mkdir -p $BASEDIR/usr/share/stagehand/plugins

#cat qtlibs | while read i;do
#  cp -R --parents $QT5_ROOT/$i* $BASEDIR/usr/share/stagehand/;done
cp -R $QT5_ROOT/lib $BASEDIR/usr/share/stagehand/
cp -R $QT5_ROOT/plugins $BASEDIR/usr/share/stagehand/

echo "Installed-Size: "`du -s -k $BASEDIR | awk '{ print $1 }'` >> $BASEDIR/DEBIAN/control

fakeroot dpkg-deb --build $BASEDIR
