#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp $SCRIPT_DIR/stagehand.png ~/.local/share/icons/
export DESKTOP_FILE=~/.local/share/applications/stagehand.desktop
echo -e "[Desktop Entry]\nType=Application\nName=Stagehand\nIcon=stagehand.png" > $DESKTOP_FILE
echo "Exec="`pwd`"/stagehand" >> $DESKTOP_FILE
