#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export LD_LIBRARY_PATH=$DIR/lib
export QT_PLUGIN_PATH=$DIR/plugins

# apply any updates
if [ -d update ]
then
  cp -dfvR update/* .
  rm -rf update
fi
$DIR/bin/stagehand $*
